### ISSUE TITLE
Make kart an admin of this repo

### ISSUE THREAD

**Issue by jonathankart** [ahmsolo/lytefoot#2]
please
thank you

**Comment by jonathankart** [comment]
there is a settings link on the bottom right from the repo home page (https://github.com/ahmsolo/lytefoot)
<img width="323" alt="screen shot 2015-07-16 at 11 52 33 am" src="https://cloud.githubusercontent.com/assets/1466814/8786391/b76969b4-2ee2-11e5-8b4f-fdbb367791d8.png">

click that and then collaborators.  maybe in there is an option for making me an admin

**Comment by ahmsolo** [comment]
no
1) why did you send me a motif screenshot
2) you can't do anything after settings->collaborators

  i don't see an admin tab https://github.com/blog/44-repository-admin-tab

**Comment by ahmsolo** [comment]
made you guys admins under the birdicles org
closing
